#!/bin/bash

die(){ echo "$*" >&2; exit 1; }

BACKUP="$0"

command -v restic &>/dev/null \
	|| die 'Cannot find restic executable!'

BACKUP_CONF="${BACKUP_CONF:-default}"

if [ -r "$HOME/.config/backup/${BACKUP_CONF}.env" ]; then
	CONFIG_BASE="$HOME/.config/backup"
elif [ -r "/etc/backup/${BACKUP_CONF}.env" ]; then
	CONFIG_BASE="/etc/backup"
else
	die "Configuration '${BACKUP_CONF}' does not exist."
fi

if [ -e "${CONFIG_BASE}/${BACKUP_CONF}.exclude" ]; then
	EXCLUDE_FILE="${CONFIG_BASE}/${BACKUP_CONF}.exclude"
fi

. "${CONFIG_BASE}/${BACKUP_CONF}.env" || die "Could not read envfile."

case "$1" in

	do-backup)
		restic backup \
			-x \
			${OPT_RESTIC} ${OPT_RESTIC_BACKUP} \
			${EXCLUDE_FILE:+--exclude-file=${EXCLUDE_FILE}} \
			${SOURCES[@]:-/}
		;;

	do-forget)
		restic forget \
			${OPT_RESTIC} ${OPT_RESTIC_FORGET} \
			${KEEP_TAG:+--keep-tag ${KEEP_TAG}} \
			${KEEP_WITHIN:+--keep-within ${KEEP_WITHIN}} \
			${KEEP_DAILY:+--keep-daily ${KEEP_DAILY}} \
			${KEEP_WEEKLY:+--keep-weekly ${KEEP_WEEKLY}} \
			${KEEP_MONTHLY:+--keep-monthly ${KEEP_MONTHLY}} \
			${KEEP_YEARLY:+--keep-yearly ${KEEP_YEARLY}} \
			${KEEP_LAST:+--keep-last ${KEEP_LAST}}
		;;

	run|"")
		"${BACKUP}" do-backup \
		|| die "restic failed to create snapshot."
		"${BACKUP}" do-forget \
		|| die "restic failed to forget snapshots"
		;;
	*)
		restic ${OPT_RESTIC} $*
		;;
esac
